/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.kt

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'com.kt.greeting' plugin.
 */
public class DevopsPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.kt.devops")

        then:
        project.tasks.findByName("devops") != null
    }
}
